export const APP_CONSTANTS = {
    HOST: 'http://127.0.0.1',

    REGISTRATION_FORM: 'REGISTRATION_FORM',
    CREATE_ROOM_FORM: 'CREATE_ROOM_FORM',
    JOIN_TO_ROOM: 'JOIN_TO_ROOM',

    USER_FORM_SWITCH: 'USER_FORM_SWITCH',

    API_USERS: '/api/users',
    API_ROOMS: 'api/game-rooms'
}

 