export const ACTION_TYPE = {
    CLICK_INCREASE: "CLICK_INCREASE",
    CLICK_DECREASE: "CLICK_DECREASE",

    SWITCH_USER_FORM: "SWITCH_USER_FORM",

    USER_CHECK_AUTH: 'USER_CHECK_AUTH',
    LOG_OUT_USER: 'LOG_OUT_USER',
    // LOG_IN_USER: 'LOG_IN_USER'

    GET_ALL_GAME_ROOMS: 'GET_ALL_GAME_ROOMS'
}